name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: server

      - name: Build server
        run: npm run build
        working-directory: server

      - name: Test server
        run: npm run test
        working-directory: server
