name: github-actions
on: [push]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/server

      - name: Build server
        run: npm run build
        working-directory: packages/server
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/client

      - name: Build client
        run: npm run build
        working-directory: packages/client
